---
- hosts: 'all'
  tasks:
  - name: 'Enviando el fichero'
    copy:
      src: /etc/ansible/examples/hosts
      dest: /etc/hosts
      owner: root
      group: root
      mode: '0644'
      backup: yes
